sudo: false

matrix:
  include:

    # Builds with wasm-pack.
    - language: rust
      rust: beta
      env: RUST_BACKTRACE=1
      addons:
        firefox: latest
        chrome: stable
      before_script:
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
      script:
        - wasm-pack build --target web
        - wasm-pack test --chrome --firefox --headless

    # Builds with webpack.
    - language: node_js
      node_js: "10"
      before_script:
        - cd ./www
        - npm install
        - npm audit fix
      script:
        - ./node_modules/.bin/webpack