os: linux
dist: focal

language: rust
rust: stable

addons:
  firefox: latest
  chrome: stable

install:
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
  - nvm install node
  - nvm use node
  - npm install -g typescript
  - cd www

script:
  - wasm-pack build
  - npm install
  - npm audit fix
  - tsc --build src/ts/tsconfig.json
  - wasm-pack test --firefox --headless
  - wasm-pack test --chrome  --headless
  - ./node_modules/.bin/webpack