os: linux
dist: focal

language: [rust, node_js]

jobs:
  include:

    # Builds with wasm-pack and webpack.
    rust: stable
    node_js: "14"
    env: RUST_BACKTRACE=1
    addons:
      firefox: latest
      chrome: stable
    before_script:
      - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
    script:
      - wasm-pack build
      - wasm-pack test --chrome --firefox --headless
      - cd ./www
      - npm install
      - npm audit fix
      - ./node_modules/.bin/webpack