language: rust
sudo: false

cache: cargo

matrix:
  include:

    # Builds with wasm-pack.
    - rust: beta
      env: RUST_BACKTRACE=1
      addons:
        firefox: latest
        chrome: stable
      before_script:
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
      script:
        - wasm-pack build --target web
        - wasm-pack test --chrome --firefox --headless